//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Contests.Core.Repository
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CoreEntities object using the connection string found in the 'CoreEntities' section of the application configuration file.
        /// </summary>
        public CoreEntities() : base("name=CoreEntities", "CoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CoreEntities object.
        /// </summary>
        public CoreEntities(string connectionString) : base(connectionString, "CoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CoreEntities object.
        /// </summary>
        public CoreEntities(EntityConnection connection) : base(connection, "CoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<JUSER> JUSERs
        {
            get
            {
                if ((_JUSERs == null))
                {
                    _JUSERs = base.CreateObjectSet<JUSER>("JUSERs");
                }
                return _JUSERs;
            }
        }
        private ObjectSet<JUSER> _JUSERs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the JUSERs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJUSERs(JUSER jUSER)
        {
            base.AddObject("JUSERs", jUSER);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContestModel", Name="JUSER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class JUSER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new JUSER object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="locationSort">Initial value of the LocationSort property.</param>
        public static JUSER CreateJUSER(global::System.Int32 userID, global::System.String userName, global::System.String locationSort)
        {
            JUSER jUSER = new JUSER();
            jUSER.UserID = userID;
            jUSER.UserName = userName;
            jUSER.LocationSort = locationSort;
            return jUSER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ActiveFlag
        {
            get
            {
                return _ActiveFlag;
            }
            set
            {
                OnActiveFlagChanging(value);
                ReportPropertyChanging("ActiveFlag");
                _ActiveFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActiveFlag");
                OnActiveFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _ActiveFlag;
        partial void OnActiveFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pod
        {
            get
            {
                return _Pod;
            }
            set
            {
                OnPodChanging(value);
                ReportPropertyChanging("Pod");
                _Pod = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pod");
                OnPodChanged();
            }
        }
        private global::System.String _Pod;
        partial void OnPodChanging(global::System.String value);
        partial void OnPodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CellPhone
        {
            get
            {
                return _CellPhone;
            }
            set
            {
                OnCellPhoneChanging(value);
                ReportPropertyChanging("CellPhone");
                _CellPhone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CellPhone");
                OnCellPhoneChanged();
            }
        }
        private Nullable<global::System.Decimal> _CellPhone;
        partial void OnCellPhoneChanging(Nullable<global::System.Decimal> value);
        partial void OnCellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HomePhone
        {
            get
            {
                return _HomePhone;
            }
            set
            {
                OnHomePhoneChanging(value);
                ReportPropertyChanging("HomePhone");
                _HomePhone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HomePhone");
                OnHomePhoneChanged();
            }
        }
        private Nullable<global::System.Decimal> _HomePhone;
        partial void OnHomePhoneChanging(Nullable<global::System.Decimal> value);
        partial void OnHomePhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> BBSBanFlag
        {
            get
            {
                return _BBSBanFlag;
            }
            set
            {
                OnBBSBanFlagChanging(value);
                ReportPropertyChanging("BBSBanFlag");
                _BBSBanFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BBSBanFlag");
                OnBBSBanFlagChanged();
            }
        }
        private Nullable<global::System.Boolean> _BBSBanFlag;
        partial void OnBBSBanFlagChanging(Nullable<global::System.Boolean> value);
        partial void OnBBSBanFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> BdayMonth
        {
            get
            {
                return _BdayMonth;
            }
            set
            {
                OnBdayMonthChanging(value);
                ReportPropertyChanging("BdayMonth");
                _BdayMonth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BdayMonth");
                OnBdayMonthChanged();
            }
        }
        private Nullable<global::System.Byte> _BdayMonth;
        partial void OnBdayMonthChanging(Nullable<global::System.Byte> value);
        partial void OnBdayMonthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> BdayDay
        {
            get
            {
                return _BdayDay;
            }
            set
            {
                OnBdayDayChanging(value);
                ReportPropertyChanging("BdayDay");
                _BdayDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BdayDay");
                OnBdayDayChanged();
            }
        }
        private Nullable<global::System.Byte> _BdayDay;
        partial void OnBdayDayChanging(Nullable<global::System.Byte> value);
        partial void OnBdayDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> AnnvMonth
        {
            get
            {
                return _AnnvMonth;
            }
            set
            {
                OnAnnvMonthChanging(value);
                ReportPropertyChanging("AnnvMonth");
                _AnnvMonth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnnvMonth");
                OnAnnvMonthChanged();
            }
        }
        private Nullable<global::System.Byte> _AnnvMonth;
        partial void OnAnnvMonthChanging(Nullable<global::System.Byte> value);
        partial void OnAnnvMonthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> AnnvDay
        {
            get
            {
                return _AnnvDay;
            }
            set
            {
                OnAnnvDayChanging(value);
                ReportPropertyChanging("AnnvDay");
                _AnnvDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnnvDay");
                OnAnnvDayChanged();
            }
        }
        private Nullable<global::System.Byte> _AnnvDay;
        partial void OnAnnvDayChanging(Nullable<global::System.Byte> value);
        partial void OnAnnvDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Spouse
        {
            get
            {
                return _Spouse;
            }
            set
            {
                OnSpouseChanging(value);
                ReportPropertyChanging("Spouse");
                _Spouse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Spouse");
                OnSpouseChanged();
            }
        }
        private global::System.String _Spouse;
        partial void OnSpouseChanging(global::System.String value);
        partial void OnSpouseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> LoyaltyUpdated
        {
            get
            {
                return _LoyaltyUpdated;
            }
            set
            {
                OnLoyaltyUpdatedChanging(value);
                ReportPropertyChanging("LoyaltyUpdated");
                _LoyaltyUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoyaltyUpdated");
                OnLoyaltyUpdatedChanged();
            }
        }
        private Nullable<global::System.Int16> _LoyaltyUpdated;
        partial void OnLoyaltyUpdatedChanging(Nullable<global::System.Int16> value);
        partial void OnLoyaltyUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MLB
        {
            get
            {
                return _MLB;
            }
            set
            {
                OnMLBChanging(value);
                ReportPropertyChanging("MLB");
                _MLB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MLB");
                OnMLBChanged();
            }
        }
        private global::System.String _MLB;
        partial void OnMLBChanging(global::System.String value);
        partial void OnMLBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NFL
        {
            get
            {
                return _NFL;
            }
            set
            {
                OnNFLChanging(value);
                ReportPropertyChanging("NFL");
                _NFL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NFL");
                OnNFLChanged();
            }
        }
        private global::System.String _NFL;
        partial void OnNFLChanging(global::System.String value);
        partial void OnNFLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NCF
        {
            get
            {
                return _NCF;
            }
            set
            {
                OnNCFChanging(value);
                ReportPropertyChanging("NCF");
                _NCF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NCF");
                OnNCFChanged();
            }
        }
        private global::System.String _NCF;
        partial void OnNCFChanging(global::System.String value);
        partial void OnNCFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NCB
        {
            get
            {
                return _NCB;
            }
            set
            {
                OnNCBChanging(value);
                ReportPropertyChanging("NCB");
                _NCB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NCB");
                OnNCBChanged();
            }
        }
        private global::System.String _NCB;
        partial void OnNCBChanging(global::System.String value);
        partial void OnNCBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NBA
        {
            get
            {
                return _NBA;
            }
            set
            {
                OnNBAChanging(value);
                ReportPropertyChanging("NBA");
                _NBA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NBA");
                OnNBAChanged();
            }
        }
        private global::System.String _NBA;
        partial void OnNBAChanging(global::System.String value);
        partial void OnNBAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NHL
        {
            get
            {
                return _NHL;
            }
            set
            {
                OnNHLChanging(value);
                ReportPropertyChanging("NHL");
                _NHL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NHL");
                OnNHLChanged();
            }
        }
        private global::System.String _NHL;
        partial void OnNHLChanging(global::System.String value);
        partial void OnNHLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Website
        {
            get
            {
                return _Website;
            }
            set
            {
                OnWebsiteChanging(value);
                ReportPropertyChanging("Website");
                _Website = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Website");
                OnWebsiteChanged();
            }
        }
        private global::System.String _Website;
        partial void OnWebsiteChanging(global::System.String value);
        partial void OnWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LocationSort
        {
            get
            {
                return _LocationSort;
            }
            set
            {
                OnLocationSortChanging(value);
                ReportPropertyChanging("LocationSort");
                _LocationSort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LocationSort");
                OnLocationSortChanged();
            }
        }
        private global::System.String _LocationSort;
        partial void OnLocationSortChanging(global::System.String value);
        partial void OnLocationSortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> Reminder
        {
            get
            {
                return _Reminder;
            }
            set
            {
                OnReminderChanging(value);
                ReportPropertyChanging("Reminder");
                _Reminder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reminder");
                OnReminderChanged();
            }
        }
        private Nullable<global::System.Guid> _Reminder;
        partial void OnReminderChanging(Nullable<global::System.Guid> value);
        partial void OnReminderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> FamilyID
        {
            get
            {
                return _FamilyID;
            }
            set
            {
                OnFamilyIDChanging(value);
                ReportPropertyChanging("FamilyID");
                _FamilyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FamilyID");
                OnFamilyIDChanged();
            }
        }
        private Nullable<global::System.Int16> _FamilyID;
        partial void OnFamilyIDChanging(Nullable<global::System.Int16> value);
        partial void OnFamilyIDChanged();

        #endregion
    
    }

    #endregion
    
}
