//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("JeauxDBModel", "FK_COLFOOT_TEAM", "COLFOOT_TEAM", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Contests.NCAAF.Core.COLFOOT_TEAM), "COLFOOT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Contests.NCAAF.Core.COLFOOT), true)]

#endregion

namespace Contests.NCAAF.Core
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class JeauxDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new JeauxDBEntities object using the connection string found in the 'JeauxDBEntities' section of the application configuration file.
        /// </summary>
        public JeauxDBEntities() : base("name=JeauxDBEntities", "JeauxDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JeauxDBEntities object.
        /// </summary>
        public JeauxDBEntities(string connectionString) : base(connectionString, "JeauxDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JeauxDBEntities object.
        /// </summary>
        public JeauxDBEntities(EntityConnection connection) : base(connection, "JeauxDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<COLFOOT> COLFOOT
        {
            get
            {
                if ((_COLFOOT == null))
                {
                    _COLFOOT = base.CreateObjectSet<COLFOOT>("COLFOOT");
                }
                return _COLFOOT;
            }
        }
        private ObjectSet<COLFOOT> _COLFOOT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<COLFOOT_TEAM> COLFOOT_TEAM
        {
            get
            {
                if ((_COLFOOT_TEAM == null))
                {
                    _COLFOOT_TEAM = base.CreateObjectSet<COLFOOT_TEAM>("COLFOOT_TEAM");
                }
                return _COLFOOT_TEAM;
            }
        }
        private ObjectSet<COLFOOT_TEAM> _COLFOOT_TEAM;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<COLFOOT_WEEK> COLFOOT_WEEK
        {
            get
            {
                if ((_COLFOOT_WEEK == null))
                {
                    _COLFOOT_WEEK = base.CreateObjectSet<COLFOOT_WEEK>("COLFOOT_WEEK");
                }
                return _COLFOOT_WEEK;
            }
        }
        private ObjectSet<COLFOOT_WEEK> _COLFOOT_WEEK;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the COLFOOT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCOLFOOT(COLFOOT cOLFOOT)
        {
            base.AddObject("COLFOOT", cOLFOOT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the COLFOOT_TEAM EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCOLFOOT_TEAM(COLFOOT_TEAM cOLFOOT_TEAM)
        {
            base.AddObject("COLFOOT_TEAM", cOLFOOT_TEAM);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the COLFOOT_WEEK EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCOLFOOT_WEEK(COLFOOT_WEEK cOLFOOT_WEEK)
        {
            base.AddObject("COLFOOT_WEEK", cOLFOOT_WEEK);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JeauxDBModel", Name="COLFOOT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COLFOOT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new COLFOOT object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="teamID">Initial value of the TeamID property.</param>
        /// <param name="week">Initial value of the Week property.</param>
        public static COLFOOT CreateCOLFOOT(global::System.Int32 userID, global::System.Int16 teamID, global::System.Byte week)
        {
            COLFOOT cOLFOOT = new COLFOOT();
            cOLFOOT.UserID = userID;
            cOLFOOT.TeamID = teamID;
            cOLFOOT.Week = week;
            return cOLFOOT;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, "UserID");
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TeamID
        {
            get
            {
                return _TeamID;
            }
            set
            {
                if (_TeamID != value)
                {
                    OnTeamIDChanging(value);
                    ReportPropertyChanging("TeamID");
                    _TeamID = StructuralObject.SetValidValue(value, "TeamID");
                    ReportPropertyChanged("TeamID");
                    OnTeamIDChanged();
                }
            }
        }
        private global::System.Int16 _TeamID;
        partial void OnTeamIDChanging(global::System.Int16 value);
        partial void OnTeamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Week
        {
            get
            {
                return _Week;
            }
            set
            {
                if (_Week != value)
                {
                    OnWeekChanging(value);
                    ReportPropertyChanging("Week");
                    _Week = StructuralObject.SetValidValue(value, "Week");
                    ReportPropertyChanged("Week");
                    OnWeekChanged();
                }
            }
        }
        private global::System.Byte _Week;
        partial void OnWeekChanging(global::System.Byte value);
        partial void OnWeekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Points
        {
            get
            {
                return _Points;
            }
            set
            {
                OnPointsChanging(value);
                ReportPropertyChanging("Points");
                _Points = StructuralObject.SetValidValue(value, "Points");
                ReportPropertyChanged("Points");
                OnPointsChanged();
            }
        }
        private Nullable<global::System.Int16> _Points;
        partial void OnPointsChanging(Nullable<global::System.Int16> value);
        partial void OnPointsChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JeauxDBModel", "FK_COLFOOT_TEAM", "COLFOOT_TEAM")]
        public COLFOOT_TEAM COLFOOT_TEAM
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COLFOOT_TEAM>("JeauxDBModel.FK_COLFOOT_TEAM", "COLFOOT_TEAM").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COLFOOT_TEAM>("JeauxDBModel.FK_COLFOOT_TEAM", "COLFOOT_TEAM").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<COLFOOT_TEAM> COLFOOT_TEAMReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<COLFOOT_TEAM>("JeauxDBModel.FK_COLFOOT_TEAM", "COLFOOT_TEAM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<COLFOOT_TEAM>("JeauxDBModel.FK_COLFOOT_TEAM", "COLFOOT_TEAM", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JeauxDBModel", Name="COLFOOT_TEAM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COLFOOT_TEAM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new COLFOOT_TEAM object.
        /// </summary>
        /// <param name="teamID">Initial value of the TeamID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static COLFOOT_TEAM CreateCOLFOOT_TEAM(global::System.Int16 teamID, global::System.String name)
        {
            COLFOOT_TEAM cOLFOOT_TEAM = new COLFOOT_TEAM();
            cOLFOOT_TEAM.TeamID = teamID;
            cOLFOOT_TEAM.Name = name;
            return cOLFOOT_TEAM;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TeamID
        {
            get
            {
                return _TeamID;
            }
            set
            {
                if (_TeamID != value)
                {
                    OnTeamIDChanging(value);
                    ReportPropertyChanging("TeamID");
                    _TeamID = StructuralObject.SetValidValue(value, "TeamID");
                    ReportPropertyChanged("TeamID");
                    OnTeamIDChanged();
                }
            }
        }
        private global::System.Int16 _TeamID;
        partial void OnTeamIDChanging(global::System.Int16 value);
        partial void OnTeamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Conference
        {
            get
            {
                return _Conference;
            }
            set
            {
                OnConferenceChanging(value);
                ReportPropertyChanging("Conference");
                _Conference = StructuralObject.SetValidValue(value, true, "Conference");
                ReportPropertyChanged("Conference");
                OnConferenceChanged();
            }
        }
        private global::System.String _Conference;
        partial void OnConferenceChanging(global::System.String value);
        partial void OnConferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OPrice
        {
            get
            {
                return _OPrice;
            }
            set
            {
                OnOPriceChanging(value);
                ReportPropertyChanging("OPrice");
                _OPrice = StructuralObject.SetValidValue(value, "OPrice");
                ReportPropertyChanged("OPrice");
                OnOPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _OPrice;
        partial void OnOPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnOPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Wins
        {
            get
            {
                return _Wins;
            }
            set
            {
                OnWinsChanging(value);
                ReportPropertyChanging("Wins");
                _Wins = StructuralObject.SetValidValue(value, "Wins");
                ReportPropertyChanged("Wins");
                OnWinsChanged();
            }
        }
        private Nullable<global::System.Int16> _Wins;
        partial void OnWinsChanging(Nullable<global::System.Int16> value);
        partial void OnWinsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Losses
        {
            get
            {
                return _Losses;
            }
            set
            {
                OnLossesChanging(value);
                ReportPropertyChanging("Losses");
                _Losses = StructuralObject.SetValidValue(value, "Losses");
                ReportPropertyChanged("Losses");
                OnLossesChanged();
            }
        }
        private Nullable<global::System.Int16> _Losses;
        partial void OnLossesChanging(Nullable<global::System.Int16> value);
        partial void OnLossesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Points
        {
            get
            {
                return _Points;
            }
            set
            {
                OnPointsChanging(value);
                ReportPropertyChanging("Points");
                _Points = StructuralObject.SetValidValue(value, "Points");
                ReportPropertyChanged("Points");
                OnPointsChanged();
            }
        }
        private Nullable<global::System.Int16> _Points;
        partial void OnPointsChanging(Nullable<global::System.Int16> value);
        partial void OnPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> OwnedBy
        {
            get
            {
                return _OwnedBy;
            }
            set
            {
                OnOwnedByChanging(value);
                ReportPropertyChanging("OwnedBy");
                _OwnedBy = StructuralObject.SetValidValue(value, "OwnedBy");
                ReportPropertyChanged("OwnedBy");
                OnOwnedByChanged();
            }
        }
        private Nullable<global::System.Int16> _OwnedBy;
        partial void OnOwnedByChanging(Nullable<global::System.Int16> value);
        partial void OnOwnedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RealValue
        {
            get
            {
                return _RealValue;
            }
            set
            {
                OnRealValueChanging(value);
                ReportPropertyChanging("RealValue");
                _RealValue = StructuralObject.SetValidValue(value, "RealValue");
                ReportPropertyChanged("RealValue");
                OnRealValueChanged();
            }
        }
        private Nullable<global::System.Decimal> _RealValue;
        partial void OnRealValueChanging(Nullable<global::System.Decimal> value);
        partial void OnRealValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSelectable
        {
            get
            {
                return _IsSelectable;
            }
            set
            {
                OnIsSelectableChanging(value);
                ReportPropertyChanging("IsSelectable");
                _IsSelectable = StructuralObject.SetValidValue(value, "IsSelectable");
                ReportPropertyChanged("IsSelectable");
                OnIsSelectableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSelectable;
        partial void OnIsSelectableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSelectableChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JeauxDBModel", "FK_COLFOOT_TEAM", "COLFOOT")]
        public EntityCollection<COLFOOT> COLFeet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<COLFOOT>("JeauxDBModel.FK_COLFOOT_TEAM", "COLFOOT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<COLFOOT>("JeauxDBModel.FK_COLFOOT_TEAM", "COLFOOT", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JeauxDBModel", Name="COLFOOT_WEEK")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class COLFOOT_WEEK : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new COLFOOT_WEEK object.
        /// </summary>
        /// <param name="currentWeek">Initial value of the CurrentWeek property.</param>
        public static COLFOOT_WEEK CreateCOLFOOT_WEEK(global::System.Byte currentWeek)
        {
            COLFOOT_WEEK cOLFOOT_WEEK = new COLFOOT_WEEK();
            cOLFOOT_WEEK.CurrentWeek = currentWeek;
            return cOLFOOT_WEEK;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CurrentWeek
        {
            get
            {
                return _CurrentWeek;
            }
            set
            {
                if (_CurrentWeek != value)
                {
                    OnCurrentWeekChanging(value);
                    ReportPropertyChanging("CurrentWeek");
                    _CurrentWeek = StructuralObject.SetValidValue(value, "CurrentWeek");
                    ReportPropertyChanged("CurrentWeek");
                    OnCurrentWeekChanged();
                }
            }
        }
        private global::System.Byte _CurrentWeek;
        partial void OnCurrentWeekChanging(global::System.Byte value);
        partial void OnCurrentWeekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TueGames
        {
            get
            {
                return _TueGames;
            }
            set
            {
                OnTueGamesChanging(value);
                ReportPropertyChanging("TueGames");
                _TueGames = StructuralObject.SetValidValue(value, true, "TueGames");
                ReportPropertyChanged("TueGames");
                OnTueGamesChanged();
            }
        }
        private global::System.String _TueGames;
        partial void OnTueGamesChanging(global::System.String value);
        partial void OnTueGamesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WedGames
        {
            get
            {
                return _WedGames;
            }
            set
            {
                OnWedGamesChanging(value);
                ReportPropertyChanging("WedGames");
                _WedGames = StructuralObject.SetValidValue(value, true, "WedGames");
                ReportPropertyChanged("WedGames");
                OnWedGamesChanged();
            }
        }
        private global::System.String _WedGames;
        partial void OnWedGamesChanging(global::System.String value);
        partial void OnWedGamesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThurGames
        {
            get
            {
                return _ThurGames;
            }
            set
            {
                OnThurGamesChanging(value);
                ReportPropertyChanging("ThurGames");
                _ThurGames = StructuralObject.SetValidValue(value, true, "ThurGames");
                ReportPropertyChanged("ThurGames");
                OnThurGamesChanged();
            }
        }
        private global::System.String _ThurGames;
        partial void OnThurGamesChanging(global::System.String value);
        partial void OnThurGamesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FriGames
        {
            get
            {
                return _FriGames;
            }
            set
            {
                OnFriGamesChanging(value);
                ReportPropertyChanging("FriGames");
                _FriGames = StructuralObject.SetValidValue(value, true, "FriGames");
                ReportPropertyChanged("FriGames");
                OnFriGamesChanged();
            }
        }
        private global::System.String _FriGames;
        partial void OnFriGamesChanging(global::System.String value);
        partial void OnFriGamesChanged();

        #endregion

    }

    #endregion

}
