//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NCAAFModel", "AwayTeam", "Team", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Contests.NCAAF.Core.Team), "Schedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Contests.NCAAF.Core.Schedule), true)]
[assembly: EdmRelationshipAttribute("NCAAFModel", "FK_Schedule_Week", "Week", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Contests.NCAAF.Core.Week), "Schedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Contests.NCAAF.Core.Schedule), true)]
[assembly: EdmRelationshipAttribute("NCAAFModel", "HomeTeam", "Team", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Contests.NCAAF.Core.Team), "Schedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Contests.NCAAF.Core.Schedule), true)]

#endregion

namespace Contests.NCAAF.Core
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NCAAFEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NCAAFEntities object using the connection string found in the 'NCAAFEntities' section of the application configuration file.
        /// </summary>
        public NCAAFEntities() : base("name=NCAAFEntities", "NCAAFEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NCAAFEntities object.
        /// </summary>
        public NCAAFEntities(string connectionString) : base(connectionString, "NCAAFEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NCAAFEntities object.
        /// </summary>
        public NCAAFEntities(EntityConnection connection) : base(connection, "NCAAFEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Schedule> Schedules
        {
            get
            {
                if ((_Schedules == null))
                {
                    _Schedules = base.CreateObjectSet<Schedule>("Schedules");
                }
                return _Schedules;
            }
        }
        private ObjectSet<Schedule> _Schedules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Team> Teams
        {
            get
            {
                if ((_Teams == null))
                {
                    _Teams = base.CreateObjectSet<Team>("Teams");
                }
                return _Teams;
            }
        }
        private ObjectSet<Team> _Teams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Week> Weeks
        {
            get
            {
                if ((_Weeks == null))
                {
                    _Weeks = base.CreateObjectSet<Week>("Weeks");
                }
                return _Weeks;
            }
        }
        private ObjectSet<Week> _Weeks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_schedule> vw_schedule
        {
            get
            {
                if ((_vw_schedule == null))
                {
                    _vw_schedule = base.CreateObjectSet<vw_schedule>("vw_schedule");
                }
                return _vw_schedule;
            }
        }
        private ObjectSet<vw_schedule> _vw_schedule;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TEAM_SCHEDULE> TEAM_SCHEDULE
        {
            get
            {
                if ((_TEAM_SCHEDULE == null))
                {
                    _TEAM_SCHEDULE = base.CreateObjectSet<TEAM_SCHEDULE>("TEAM_SCHEDULE");
                }
                return _TEAM_SCHEDULE;
            }
        }
        private ObjectSet<TEAM_SCHEDULE> _TEAM_SCHEDULE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USER_SCHEDULE> USER_SCHEDULE
        {
            get
            {
                if ((_USER_SCHEDULE == null))
                {
                    _USER_SCHEDULE = base.CreateObjectSet<USER_SCHEDULE>("USER_SCHEDULE");
                }
                return _USER_SCHEDULE;
            }
        }
        private ObjectSet<USER_SCHEDULE> _USER_SCHEDULE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USER_WEEKLY_SCHEDULE> USER_WEEKLY_SCHEDULE
        {
            get
            {
                if ((_USER_WEEKLY_SCHEDULE == null))
                {
                    _USER_WEEKLY_SCHEDULE = base.CreateObjectSet<USER_WEEKLY_SCHEDULE>("USER_WEEKLY_SCHEDULE");
                }
                return _USER_WEEKLY_SCHEDULE;
            }
        }
        private ObjectSet<USER_WEEKLY_SCHEDULE> _USER_WEEKLY_SCHEDULE;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Schedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSchedules(Schedule schedule)
        {
            base.AddObject("Schedules", schedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Teams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeams(Team team)
        {
            base.AddObject("Teams", team);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Weeks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeeks(Week week)
        {
            base.AddObject("Weeks", week);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vw_schedule EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_schedule(vw_schedule vw_schedule)
        {
            base.AddObject("vw_schedule", vw_schedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TEAM_SCHEDULE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTEAM_SCHEDULE(TEAM_SCHEDULE tEAM_SCHEDULE)
        {
            base.AddObject("TEAM_SCHEDULE", tEAM_SCHEDULE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USER_SCHEDULE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSER_SCHEDULE(USER_SCHEDULE uSER_SCHEDULE)
        {
            base.AddObject("USER_SCHEDULE", uSER_SCHEDULE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USER_WEEKLY_SCHEDULE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSER_WEEKLY_SCHEDULE(USER_WEEKLY_SCHEDULE uSER_WEEKLY_SCHEDULE)
        {
            base.AddObject("USER_WEEKLY_SCHEDULE", uSER_WEEKLY_SCHEDULE);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NCAAFModel", Name="Schedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Schedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Schedule object.
        /// </summary>
        /// <param name="homeTeamId">Initial value of the HomeTeamId property.</param>
        /// <param name="awayTeamId">Initial value of the AwayTeamId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Schedule CreateSchedule(global::System.Int32 homeTeamId, global::System.Int32 awayTeamId, global::System.DateTime date)
        {
            Schedule schedule = new Schedule();
            schedule.HomeTeamId = homeTeamId;
            schedule.AwayTeamId = awayTeamId;
            schedule.Date = date;
            return schedule;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HomeTeamId
        {
            get
            {
                return _HomeTeamId;
            }
            set
            {
                if (_HomeTeamId != value)
                {
                    OnHomeTeamIdChanging(value);
                    ReportPropertyChanging("HomeTeamId");
                    _HomeTeamId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HomeTeamId");
                    OnHomeTeamIdChanged();
                }
            }
        }
        private global::System.Int32 _HomeTeamId;
        partial void OnHomeTeamIdChanging(global::System.Int32 value);
        partial void OnHomeTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AwayTeamId
        {
            get
            {
                return _AwayTeamId;
            }
            set
            {
                if (_AwayTeamId != value)
                {
                    OnAwayTeamIdChanging(value);
                    ReportPropertyChanging("AwayTeamId");
                    _AwayTeamId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AwayTeamId");
                    OnAwayTeamIdChanged();
                }
            }
        }
        private global::System.Int32 _AwayTeamId;
        partial void OnAwayTeamIdChanging(global::System.Int32 value);
        partial void OnAwayTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Week
        {
            get
            {
                return _Week;
            }
            set
            {
                OnWeekChanging(value);
                ReportPropertyChanging("Week");
                _Week = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Week");
                OnWeekChanged();
            }
        }
        private Nullable<global::System.Int32> _Week;
        partial void OnWeekChanging(Nullable<global::System.Int32> value);
        partial void OnWeekChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NCAAFModel", "AwayTeam", "Team")]
        public Team AwayTeam
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("NCAAFModel.AwayTeam", "Team").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("NCAAFModel.AwayTeam", "Team").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Team> AwayTeamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("NCAAFModel.AwayTeam", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Team>("NCAAFModel.AwayTeam", "Team", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NCAAFModel", "FK_Schedule_Week", "Week")]
        public Week ScheduleWeek
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Week>("NCAAFModel.FK_Schedule_Week", "Week").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Week>("NCAAFModel.FK_Schedule_Week", "Week").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Week> ScheduleWeekReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Week>("NCAAFModel.FK_Schedule_Week", "Week");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Week>("NCAAFModel.FK_Schedule_Week", "Week", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NCAAFModel", "HomeTeam", "Team")]
        public Team HomeTeam
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("NCAAFModel.HomeTeam", "Team").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("NCAAFModel.HomeTeam", "Team").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Team> HomeTeamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("NCAAFModel.HomeTeam", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Team>("NCAAFModel.HomeTeam", "Team", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NCAAFModel", Name="Team")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Team : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Team object.
        /// </summary>
        /// <param name="teamId">Initial value of the TeamId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Team CreateTeam(global::System.Int32 teamId, global::System.String name)
        {
            Team team = new Team();
            team.TeamId = teamId;
            team.Name = name;
            return team;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeamId
        {
            get
            {
                return _TeamId;
            }
            set
            {
                if (_TeamId != value)
                {
                    OnTeamIdChanging(value);
                    ReportPropertyChanging("TeamId");
                    _TeamId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TeamId");
                    OnTeamIdChanged();
                }
            }
        }
        private global::System.Int32 _TeamId;
        partial void OnTeamIdChanging(global::System.Int32 value);
        partial void OnTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSelectable
        {
            get
            {
                return _IsSelectable;
            }
            set
            {
                OnIsSelectableChanging(value);
                ReportPropertyChanging("IsSelectable");
                _IsSelectable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSelectable");
                OnIsSelectableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSelectable;
        partial void OnIsSelectableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSelectableChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NCAAFModel", "AwayTeam", "Schedule")]
        public EntityCollection<Schedule> AwaySchedule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Schedule>("NCAAFModel.AwayTeam", "Schedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Schedule>("NCAAFModel.AwayTeam", "Schedule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NCAAFModel", "HomeTeam", "Schedule")]
        public EntityCollection<Schedule> HomeSchedule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Schedule>("NCAAFModel.HomeTeam", "Schedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Schedule>("NCAAFModel.HomeTeam", "Schedule", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NCAAFModel", Name="TEAM_SCHEDULE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TEAM_SCHEDULE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TEAM_SCHEDULE object.
        /// </summary>
        /// <param name="teamID">Initial value of the TeamID property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static TEAM_SCHEDULE CreateTEAM_SCHEDULE(global::System.Int32 teamID, global::System.String name)
        {
            TEAM_SCHEDULE tEAM_SCHEDULE = new TEAM_SCHEDULE();
            tEAM_SCHEDULE.TeamID = teamID;
            tEAM_SCHEDULE.name = name;
            return tEAM_SCHEDULE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeamID
        {
            get
            {
                return _TeamID;
            }
            set
            {
                if (_TeamID != value)
                {
                    OnTeamIDChanging(value);
                    ReportPropertyChanging("TeamID");
                    _TeamID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TeamID");
                    OnTeamIDChanged();
                }
            }
        }
        private global::System.Int32 _TeamID;
        partial void OnTeamIDChanging(global::System.Int32 value);
        partial void OnTeamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week1_opponent
        {
            get
            {
                return _week1_opponent;
            }
            set
            {
                Onweek1_opponentChanging(value);
                ReportPropertyChanging("week1_opponent");
                _week1_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week1_opponent");
                Onweek1_opponentChanged();
            }
        }
        private global::System.String _week1_opponent;
        partial void Onweek1_opponentChanging(global::System.String value);
        partial void Onweek1_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week2_opponent
        {
            get
            {
                return _week2_opponent;
            }
            set
            {
                Onweek2_opponentChanging(value);
                ReportPropertyChanging("week2_opponent");
                _week2_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week2_opponent");
                Onweek2_opponentChanged();
            }
        }
        private global::System.String _week2_opponent;
        partial void Onweek2_opponentChanging(global::System.String value);
        partial void Onweek2_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week3_opponent
        {
            get
            {
                return _week3_opponent;
            }
            set
            {
                Onweek3_opponentChanging(value);
                ReportPropertyChanging("week3_opponent");
                _week3_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week3_opponent");
                Onweek3_opponentChanged();
            }
        }
        private global::System.String _week3_opponent;
        partial void Onweek3_opponentChanging(global::System.String value);
        partial void Onweek3_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week4_opponent
        {
            get
            {
                return _week4_opponent;
            }
            set
            {
                Onweek4_opponentChanging(value);
                ReportPropertyChanging("week4_opponent");
                _week4_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week4_opponent");
                Onweek4_opponentChanged();
            }
        }
        private global::System.String _week4_opponent;
        partial void Onweek4_opponentChanging(global::System.String value);
        partial void Onweek4_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week5_opponent
        {
            get
            {
                return _week5_opponent;
            }
            set
            {
                Onweek5_opponentChanging(value);
                ReportPropertyChanging("week5_opponent");
                _week5_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week5_opponent");
                Onweek5_opponentChanged();
            }
        }
        private global::System.String _week5_opponent;
        partial void Onweek5_opponentChanging(global::System.String value);
        partial void Onweek5_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week6_opponent
        {
            get
            {
                return _week6_opponent;
            }
            set
            {
                Onweek6_opponentChanging(value);
                ReportPropertyChanging("week6_opponent");
                _week6_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week6_opponent");
                Onweek6_opponentChanged();
            }
        }
        private global::System.String _week6_opponent;
        partial void Onweek6_opponentChanging(global::System.String value);
        partial void Onweek6_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week7_opponent
        {
            get
            {
                return _week7_opponent;
            }
            set
            {
                Onweek7_opponentChanging(value);
                ReportPropertyChanging("week7_opponent");
                _week7_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week7_opponent");
                Onweek7_opponentChanged();
            }
        }
        private global::System.String _week7_opponent;
        partial void Onweek7_opponentChanging(global::System.String value);
        partial void Onweek7_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week8_opponent
        {
            get
            {
                return _week8_opponent;
            }
            set
            {
                Onweek8_opponentChanging(value);
                ReportPropertyChanging("week8_opponent");
                _week8_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week8_opponent");
                Onweek8_opponentChanged();
            }
        }
        private global::System.String _week8_opponent;
        partial void Onweek8_opponentChanging(global::System.String value);
        partial void Onweek8_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week9_opponent
        {
            get
            {
                return _week9_opponent;
            }
            set
            {
                Onweek9_opponentChanging(value);
                ReportPropertyChanging("week9_opponent");
                _week9_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week9_opponent");
                Onweek9_opponentChanged();
            }
        }
        private global::System.String _week9_opponent;
        partial void Onweek9_opponentChanging(global::System.String value);
        partial void Onweek9_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week10_opponent
        {
            get
            {
                return _week10_opponent;
            }
            set
            {
                Onweek10_opponentChanging(value);
                ReportPropertyChanging("week10_opponent");
                _week10_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week10_opponent");
                Onweek10_opponentChanged();
            }
        }
        private global::System.String _week10_opponent;
        partial void Onweek10_opponentChanging(global::System.String value);
        partial void Onweek10_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week11_opponent
        {
            get
            {
                return _week11_opponent;
            }
            set
            {
                Onweek11_opponentChanging(value);
                ReportPropertyChanging("week11_opponent");
                _week11_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week11_opponent");
                Onweek11_opponentChanged();
            }
        }
        private global::System.String _week11_opponent;
        partial void Onweek11_opponentChanging(global::System.String value);
        partial void Onweek11_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week12_opponent
        {
            get
            {
                return _week12_opponent;
            }
            set
            {
                Onweek12_opponentChanging(value);
                ReportPropertyChanging("week12_opponent");
                _week12_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week12_opponent");
                Onweek12_opponentChanged();
            }
        }
        private global::System.String _week12_opponent;
        partial void Onweek12_opponentChanging(global::System.String value);
        partial void Onweek12_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week13_opponent
        {
            get
            {
                return _week13_opponent;
            }
            set
            {
                Onweek13_opponentChanging(value);
                ReportPropertyChanging("week13_opponent");
                _week13_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week13_opponent");
                Onweek13_opponentChanged();
            }
        }
        private global::System.String _week13_opponent;
        partial void Onweek13_opponentChanging(global::System.String value);
        partial void Onweek13_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week14_opponent
        {
            get
            {
                return _week14_opponent;
            }
            set
            {
                Onweek14_opponentChanging(value);
                ReportPropertyChanging("week14_opponent");
                _week14_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week14_opponent");
                Onweek14_opponentChanged();
            }
        }
        private global::System.String _week14_opponent;
        partial void Onweek14_opponentChanging(global::System.String value);
        partial void Onweek14_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week15_opponent
        {
            get
            {
                return _week15_opponent;
            }
            set
            {
                Onweek15_opponentChanging(value);
                ReportPropertyChanging("week15_opponent");
                _week15_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week15_opponent");
                Onweek15_opponentChanged();
            }
        }
        private global::System.String _week15_opponent;
        partial void Onweek15_opponentChanging(global::System.String value);
        partial void Onweek15_opponentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NCAAFModel", Name="USER_SCHEDULE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USER_SCHEDULE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USER_SCHEDULE object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="teamID">Initial value of the TeamID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="opponent">Initial value of the opponent property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="pick_week">Initial value of the pick_week property.</param>
        /// <param name="currentWeek">Initial value of the CurrentWeek property.</param>
        public static USER_SCHEDULE CreateUSER_SCHEDULE(global::System.Int32 userID, global::System.Int16 teamID, global::System.String name, global::System.String opponent, global::System.DateTime date, global::System.Byte pick_week, global::System.Byte currentWeek)
        {
            USER_SCHEDULE uSER_SCHEDULE = new USER_SCHEDULE();
            uSER_SCHEDULE.UserID = userID;
            uSER_SCHEDULE.TeamID = teamID;
            uSER_SCHEDULE.Name = name;
            uSER_SCHEDULE.opponent = opponent;
            uSER_SCHEDULE.Date = date;
            uSER_SCHEDULE.pick_week = pick_week;
            uSER_SCHEDULE.CurrentWeek = currentWeek;
            return uSER_SCHEDULE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TeamID
        {
            get
            {
                return _TeamID;
            }
            set
            {
                if (_TeamID != value)
                {
                    OnTeamIDChanging(value);
                    ReportPropertyChanging("TeamID");
                    _TeamID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TeamID");
                    OnTeamIDChanged();
                }
            }
        }
        private global::System.Int16 _TeamID;
        partial void OnTeamIDChanging(global::System.Int16 value);
        partial void OnTeamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String opponent
        {
            get
            {
                return _opponent;
            }
            set
            {
                if (_opponent != value)
                {
                    OnopponentChanging(value);
                    ReportPropertyChanging("opponent");
                    _opponent = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("opponent");
                    OnopponentChanged();
                }
            }
        }
        private global::System.String _opponent;
        partial void OnopponentChanging(global::System.String value);
        partial void OnopponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> schedule_week
        {
            get
            {
                return _schedule_week;
            }
            set
            {
                Onschedule_weekChanging(value);
                ReportPropertyChanging("schedule_week");
                _schedule_week = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("schedule_week");
                Onschedule_weekChanged();
            }
        }
        private Nullable<global::System.Int32> _schedule_week;
        partial void Onschedule_weekChanging(Nullable<global::System.Int32> value);
        partial void Onschedule_weekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte pick_week
        {
            get
            {
                return _pick_week;
            }
            set
            {
                if (_pick_week != value)
                {
                    Onpick_weekChanging(value);
                    ReportPropertyChanging("pick_week");
                    _pick_week = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pick_week");
                    Onpick_weekChanged();
                }
            }
        }
        private global::System.Byte _pick_week;
        partial void Onpick_weekChanging(global::System.Byte value);
        partial void Onpick_weekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CurrentWeek
        {
            get
            {
                return _CurrentWeek;
            }
            set
            {
                if (_CurrentWeek != value)
                {
                    OnCurrentWeekChanging(value);
                    ReportPropertyChanging("CurrentWeek");
                    _CurrentWeek = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CurrentWeek");
                    OnCurrentWeekChanged();
                }
            }
        }
        private global::System.Byte _CurrentWeek;
        partial void OnCurrentWeekChanging(global::System.Byte value);
        partial void OnCurrentWeekChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NCAAFModel", Name="USER_WEEKLY_SCHEDULE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USER_WEEKLY_SCHEDULE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USER_WEEKLY_SCHEDULE object.
        /// </summary>
        /// <param name="userid">Initial value of the userid property.</param>
        /// <param name="teamid">Initial value of the teamid property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="pick_week">Initial value of the pick_week property.</param>
        public static USER_WEEKLY_SCHEDULE CreateUSER_WEEKLY_SCHEDULE(global::System.Int32 userid, global::System.Int16 teamid, global::System.String name, global::System.Byte pick_week)
        {
            USER_WEEKLY_SCHEDULE uSER_WEEKLY_SCHEDULE = new USER_WEEKLY_SCHEDULE();
            uSER_WEEKLY_SCHEDULE.userid = userid;
            uSER_WEEKLY_SCHEDULE.teamid = teamid;
            uSER_WEEKLY_SCHEDULE.name = name;
            uSER_WEEKLY_SCHEDULE.pick_week = pick_week;
            return uSER_WEEKLY_SCHEDULE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userid
        {
            get
            {
                return _userid;
            }
            set
            {
                if (_userid != value)
                {
                    OnuseridChanging(value);
                    ReportPropertyChanging("userid");
                    _userid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userid");
                    OnuseridChanged();
                }
            }
        }
        private global::System.Int32 _userid;
        partial void OnuseridChanging(global::System.Int32 value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 teamid
        {
            get
            {
                return _teamid;
            }
            set
            {
                if (_teamid != value)
                {
                    OnteamidChanging(value);
                    ReportPropertyChanging("teamid");
                    _teamid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("teamid");
                    OnteamidChanged();
                }
            }
        }
        private global::System.Int16 _teamid;
        partial void OnteamidChanging(global::System.Int16 value);
        partial void OnteamidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte pick_week
        {
            get
            {
                return _pick_week;
            }
            set
            {
                if (_pick_week != value)
                {
                    Onpick_weekChanging(value);
                    ReportPropertyChanging("pick_week");
                    _pick_week = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pick_week");
                    Onpick_weekChanged();
                }
            }
        }
        private global::System.Byte _pick_week;
        partial void Onpick_weekChanging(global::System.Byte value);
        partial void Onpick_weekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week1_opponent
        {
            get
            {
                return _week1_opponent;
            }
            set
            {
                Onweek1_opponentChanging(value);
                ReportPropertyChanging("week1_opponent");
                _week1_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week1_opponent");
                Onweek1_opponentChanged();
            }
        }
        private global::System.String _week1_opponent;
        partial void Onweek1_opponentChanging(global::System.String value);
        partial void Onweek1_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week2_opponent
        {
            get
            {
                return _week2_opponent;
            }
            set
            {
                Onweek2_opponentChanging(value);
                ReportPropertyChanging("week2_opponent");
                _week2_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week2_opponent");
                Onweek2_opponentChanged();
            }
        }
        private global::System.String _week2_opponent;
        partial void Onweek2_opponentChanging(global::System.String value);
        partial void Onweek2_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week3_opponent
        {
            get
            {
                return _week3_opponent;
            }
            set
            {
                Onweek3_opponentChanging(value);
                ReportPropertyChanging("week3_opponent");
                _week3_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week3_opponent");
                Onweek3_opponentChanged();
            }
        }
        private global::System.String _week3_opponent;
        partial void Onweek3_opponentChanging(global::System.String value);
        partial void Onweek3_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week4_opponent
        {
            get
            {
                return _week4_opponent;
            }
            set
            {
                Onweek4_opponentChanging(value);
                ReportPropertyChanging("week4_opponent");
                _week4_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week4_opponent");
                Onweek4_opponentChanged();
            }
        }
        private global::System.String _week4_opponent;
        partial void Onweek4_opponentChanging(global::System.String value);
        partial void Onweek4_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week5_opponent
        {
            get
            {
                return _week5_opponent;
            }
            set
            {
                Onweek5_opponentChanging(value);
                ReportPropertyChanging("week5_opponent");
                _week5_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week5_opponent");
                Onweek5_opponentChanged();
            }
        }
        private global::System.String _week5_opponent;
        partial void Onweek5_opponentChanging(global::System.String value);
        partial void Onweek5_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week6_opponent
        {
            get
            {
                return _week6_opponent;
            }
            set
            {
                Onweek6_opponentChanging(value);
                ReportPropertyChanging("week6_opponent");
                _week6_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week6_opponent");
                Onweek6_opponentChanged();
            }
        }
        private global::System.String _week6_opponent;
        partial void Onweek6_opponentChanging(global::System.String value);
        partial void Onweek6_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week7_opponent
        {
            get
            {
                return _week7_opponent;
            }
            set
            {
                Onweek7_opponentChanging(value);
                ReportPropertyChanging("week7_opponent");
                _week7_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week7_opponent");
                Onweek7_opponentChanged();
            }
        }
        private global::System.String _week7_opponent;
        partial void Onweek7_opponentChanging(global::System.String value);
        partial void Onweek7_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week8_opponent
        {
            get
            {
                return _week8_opponent;
            }
            set
            {
                Onweek8_opponentChanging(value);
                ReportPropertyChanging("week8_opponent");
                _week8_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week8_opponent");
                Onweek8_opponentChanged();
            }
        }
        private global::System.String _week8_opponent;
        partial void Onweek8_opponentChanging(global::System.String value);
        partial void Onweek8_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week9_opponent
        {
            get
            {
                return _week9_opponent;
            }
            set
            {
                Onweek9_opponentChanging(value);
                ReportPropertyChanging("week9_opponent");
                _week9_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week9_opponent");
                Onweek9_opponentChanged();
            }
        }
        private global::System.String _week9_opponent;
        partial void Onweek9_opponentChanging(global::System.String value);
        partial void Onweek9_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week10_opponent
        {
            get
            {
                return _week10_opponent;
            }
            set
            {
                Onweek10_opponentChanging(value);
                ReportPropertyChanging("week10_opponent");
                _week10_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week10_opponent");
                Onweek10_opponentChanged();
            }
        }
        private global::System.String _week10_opponent;
        partial void Onweek10_opponentChanging(global::System.String value);
        partial void Onweek10_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week11_opponent
        {
            get
            {
                return _week11_opponent;
            }
            set
            {
                Onweek11_opponentChanging(value);
                ReportPropertyChanging("week11_opponent");
                _week11_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week11_opponent");
                Onweek11_opponentChanged();
            }
        }
        private global::System.String _week11_opponent;
        partial void Onweek11_opponentChanging(global::System.String value);
        partial void Onweek11_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week12_opponent
        {
            get
            {
                return _week12_opponent;
            }
            set
            {
                Onweek12_opponentChanging(value);
                ReportPropertyChanging("week12_opponent");
                _week12_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week12_opponent");
                Onweek12_opponentChanged();
            }
        }
        private global::System.String _week12_opponent;
        partial void Onweek12_opponentChanging(global::System.String value);
        partial void Onweek12_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week13_opponent
        {
            get
            {
                return _week13_opponent;
            }
            set
            {
                Onweek13_opponentChanging(value);
                ReportPropertyChanging("week13_opponent");
                _week13_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week13_opponent");
                Onweek13_opponentChanged();
            }
        }
        private global::System.String _week13_opponent;
        partial void Onweek13_opponentChanging(global::System.String value);
        partial void Onweek13_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week14_opponent
        {
            get
            {
                return _week14_opponent;
            }
            set
            {
                Onweek14_opponentChanging(value);
                ReportPropertyChanging("week14_opponent");
                _week14_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week14_opponent");
                Onweek14_opponentChanged();
            }
        }
        private global::System.String _week14_opponent;
        partial void Onweek14_opponentChanging(global::System.String value);
        partial void Onweek14_opponentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String week15_opponent
        {
            get
            {
                return _week15_opponent;
            }
            set
            {
                Onweek15_opponentChanging(value);
                ReportPropertyChanging("week15_opponent");
                _week15_opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("week15_opponent");
                Onweek15_opponentChanged();
            }
        }
        private global::System.String _week15_opponent;
        partial void Onweek15_opponentChanging(global::System.String value);
        partial void Onweek15_opponentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NCAAFModel", Name="vw_schedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_schedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vw_schedule object.
        /// </summary>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="homeTeamId">Initial value of the HomeTeamId property.</param>
        /// <param name="homeName">Initial value of the HomeName property.</param>
        /// <param name="awayTeamId">Initial value of the AwayTeamId property.</param>
        /// <param name="awayName">Initial value of the AwayName property.</param>
        public static vw_schedule Createvw_schedule(global::System.DateTime date, global::System.Int32 homeTeamId, global::System.String homeName, global::System.Int32 awayTeamId, global::System.String awayName)
        {
            vw_schedule vw_schedule = new vw_schedule();
            vw_schedule.Date = date;
            vw_schedule.HomeTeamId = homeTeamId;
            vw_schedule.HomeName = homeName;
            vw_schedule.AwayTeamId = awayTeamId;
            vw_schedule.AwayName = awayName;
            return vw_schedule;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HomeTeamId
        {
            get
            {
                return _HomeTeamId;
            }
            set
            {
                if (_HomeTeamId != value)
                {
                    OnHomeTeamIdChanging(value);
                    ReportPropertyChanging("HomeTeamId");
                    _HomeTeamId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HomeTeamId");
                    OnHomeTeamIdChanged();
                }
            }
        }
        private global::System.Int32 _HomeTeamId;
        partial void OnHomeTeamIdChanging(global::System.Int32 value);
        partial void OnHomeTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HomeName
        {
            get
            {
                return _HomeName;
            }
            set
            {
                if (_HomeName != value)
                {
                    OnHomeNameChanging(value);
                    ReportPropertyChanging("HomeName");
                    _HomeName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("HomeName");
                    OnHomeNameChanged();
                }
            }
        }
        private global::System.String _HomeName;
        partial void OnHomeNameChanging(global::System.String value);
        partial void OnHomeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AwayTeamId
        {
            get
            {
                return _AwayTeamId;
            }
            set
            {
                if (_AwayTeamId != value)
                {
                    OnAwayTeamIdChanging(value);
                    ReportPropertyChanging("AwayTeamId");
                    _AwayTeamId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AwayTeamId");
                    OnAwayTeamIdChanged();
                }
            }
        }
        private global::System.Int32 _AwayTeamId;
        partial void OnAwayTeamIdChanging(global::System.Int32 value);
        partial void OnAwayTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AwayName
        {
            get
            {
                return _AwayName;
            }
            set
            {
                if (_AwayName != value)
                {
                    OnAwayNameChanging(value);
                    ReportPropertyChanging("AwayName");
                    _AwayName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AwayName");
                    OnAwayNameChanged();
                }
            }
        }
        private global::System.String _AwayName;
        partial void OnAwayNameChanging(global::System.String value);
        partial void OnAwayNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Week
        {
            get
            {
                return _Week;
            }
            set
            {
                OnWeekChanging(value);
                ReportPropertyChanging("Week");
                _Week = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Week");
                OnWeekChanged();
            }
        }
        private Nullable<global::System.Int32> _Week;
        partial void OnWeekChanging(Nullable<global::System.Int32> value);
        partial void OnWeekChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NCAAFModel", Name="Week")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Week : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Week object.
        /// </summary>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="beginDate">Initial value of the BeginDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        public static Week CreateWeek(global::System.Int32 number, global::System.DateTime beginDate, global::System.DateTime endDate)
        {
            Week week = new Week();
            week.Number = number;
            week.BeginDate = beginDate;
            week.EndDate = endDate;
            return week;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                if (_Number != value)
                {
                    OnNumberChanging(value);
                    ReportPropertyChanging("Number");
                    _Number = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Number");
                    OnNumberChanged();
                }
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BeginDate
        {
            get
            {
                return _BeginDate;
            }
            set
            {
                OnBeginDateChanging(value);
                ReportPropertyChanging("BeginDate");
                _BeginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginDate");
                OnBeginDateChanged();
            }
        }
        private global::System.DateTime _BeginDate;
        partial void OnBeginDateChanging(global::System.DateTime value);
        partial void OnBeginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NCAAFModel", "FK_Schedule_Week", "Schedule")]
        public EntityCollection<Schedule> Schedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Schedule>("NCAAFModel.FK_Schedule_Week", "Schedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Schedule>("NCAAFModel.FK_Schedule_Week", "Schedule", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
